vc=input("vehicle brand name=")
vn=input("vehicle model name=") 
vp=input("vehicle price=")
vk=input("vehicle running km=")
vm=input("vehicle mileage=")
vpp=input("1 liter petrolprice=")
tcp=('vk/vm')
pop=('vpp*tcp')
print("VEHICLE COMPANY NAME=",vc)
print("VEHICLE NAME--------=",vn)
print("VEHICLE PRICE-------=",vp)
print("ONE DAY RUNNING KM--=",vk)
print("VESHICLE MILEAGE-----=",vm)
print("PETROL PRICE-------=",vpp)
print("TOTAL COST OF PETROL=",tcp)
print("PRICE OF PETROL----=",pop)
