#write a program to print a student result by user.
sclname=input("enter your school name=")
nam=input("enter your name-----------=")
cls=input("enter your class----------=")
rlno=input("enter your rollnumber----=")
print('-------------------------------')
print('------YOUR SUBJECT MARKES------')
hi=int(input("enter markes of MATHEMATICS="))
ma=int(input("enter markes of SCIENCE----="))
sc=int(input("enter markes of SOCIAL SCIENCE="))
en=int(input("enter markes of ENGLISH----="))
ss=int(input("enter markes of HINDI------="))
print('EXTRA CURRICULAR ACTIVITY MARKS')
dr=int(input("enter markes of DRAWING----="))
st=int(input("enter markes of SPORTS-----="))
tot=(hi+ma+sc+en+ss+dr+st)
per=(tot/7)
print('-------------------------------')
print('TOTAL MARKS=',tot)
print('percentage=',round(per,3))#round(per,3) point ke bdme 3 no cahiye sirf isliye
